### ISSUE TITLE
for screen sizes wider than 1436, table of contents overlaps the content

### ISSUE THREAD

**Issue by hk1ll3r** [gradle-guides/creating-new-gradle-builds#11]
![gradlehelp](https://user-images.githubusercontent.com/20055055/35347086-e15b9014-00e8-11e8-9059-e97a7445d9b9.png)

Link for repro: https://guides.gradle.org/creating-new-gradle-builds/#what_you_ll_need

**Comment by eriwen** [comment]
Thank you for reporting! Can you please confirm this is fixed?

**Comment by lacasseio** [comment]
Reopen on https://github.com/gradle/guides if it's still an issue.
