### ISSUE TITLE
buildFile property explanation problem

### ISSUE THREAD

**Issue by ybasefinal** [gradle-guides/creating-new-gradle-builds#16]
"The buildFile property is fully-qualified path name to build.gradle, which resides in the buildDir — by default, the build subdirectory of the projectDir, the directory containing the build.gradle file."

Is this mean that build.gradle file resides in the build directory?

**Comment by RSLi** [comment]
I also think there's a typo here. `build.gradle` resides in `projectDir`. `buildDir` is by default `<projectDir>/build`. The first part of the sentence seems to indicate that "buildFile resides in the buildDir", which is not correct.

**Comment by lacasseio** [comment]
Issue moved to [gradle/guides #234](https://github.com/gradle/guides/issues/234) via [**ZenHub**](https://www.zenhub.com/)
