### ISSUE TITLE
More clearly distinguish between task instances and task types

### ISSUE THREAD

**Issue by adammurdoch** [gradle-guides/creating-new-gradle-builds#2]
This guide uses language like "configure a core task" but goes on to define an ad hoc _instance_ of a task using a core _task type_. This is one of the most fundamental concepts of Gradle, so I think it's important to be extremely clear in this guide.

I would structure things something like this:

- Introduce the concept of task _instances_, using the hello world example. The hello world example _defines_ an _ad hoc_ task _instance_.
- Introduce the concept of task _types_, using the copy example. This example defines an ad hoc task instance using a specific _core_ task _type.
- Introduce the concept of plugins that add task instances, using the base plugin example. This example applies a plugin, that defines a bunch of task instances of various types.

**Comment by eriwen** [comment]
I will ensure this is addressed in my PR #13

**Comment by lacasseio** [comment]
Issue moved to [gradle/guides #219](https://github.com/gradle/guides/issues/219) via [**ZenHub**](https://www.zenhub.com/)
