### ISSUE TITLE
Update guide for changes to `init` task

### ISSUE THREAD

**Issue by adammurdoch** [gradle-guides/creating-new-gradle-builds#21]
Running `gradle init` as suggested in the guide using the suggested version results in an interactive prompt, the guide should reflect this.

**Comment by wroth** [comment]
Hmm, running "gradle init" as suggested in the guide (https://guides.gradle.org/building-java-libraries/) does NOT result in an interactive prompt.  The guides are inconsistent: see https://guides.gradle.org/creating-new-gradle-builds/

Please choose one or the other (behavior) and update the doc to (consistently) match.  It's very concerning for a new user to have the very first instruction after downloading and installing gradle, fail immediately.

**Comment by adammurdoch** [comment]
@wroth definitely agree. This is not a great experience. We're gradually updating the guides so that they are consistent and accurate. At this stage this is a manual process so it takes some time. We're also adding some automation to make sure the guides remain consistent as Gradle changes.

Do you have some details about the environment you ran `gradle init` in? eg which operating system and terminal? Which Gradle version?

**Comment by wroth** [comment]
Gradle 5.5.1, Windows 10, bash under Cygwin.  (mintty?)

**Comment by adammurdoch** [comment]
Thanks for the information. Gradle was not correctly detecting that it was running from mintty. This should be fixed now (https://github.com/gradle/gradle/issues/9994).

**Comment by wroth** [comment]
Thank you!  I am frankly delighted/astonished at the rapid response to this concern.  Kudos!

**Comment by lacasseio** [comment]
Issue moved to [gradle/guides #250](https://github.com/gradle/guides/issues/250) via [**ZenHub**](https://www.zenhub.com/)
