### ISSUE TITLE
Clarify that this guide doesn't really describe the process that people should follow to create new builds

### ISSUE THREAD

**Issue by adammurdoch** [gradle-guides/creating-new-gradle-builds#22]
This guide introduces some generic capabilities but without any clear advice about when you'd use these things. Almost no-one starting with Gradle will _actually_ want to create a generic project from scratch and define a bunch of tasks, and we definitely should not be suggesting or even give the impression that they should. 

Instead, someone starting with Gradle should be applying some plugins (via the `init` task) and tweaking the settings to their liking. This guide should make it clear that if you're starting with Gradle you should use one of the other, domain specific guides to set up a Java library project or a Kotlin application or a Gradle plugin or whatever, and that this guide is intended as a tutorial on the basic concepts that the other guides sit on top of (and how you might extend them).

**Comment by lacasseio** [comment]
Issue moved to [gradle/guides #251](https://github.com/gradle/guides/issues/251) via [**ZenHub**](https://www.zenhub.com/)
