### ISSUE TITLE
Introduce applying plugins before defining new tasks

### ISSUE THREAD

**Issue by adammurdoch** [gradle-guides/creating-new-gradle-builds#23]
A new build author will much more likely be dealing with plugins and their configuration before they deal with defining new tasks. Perhaps a better order would be:

- Init the build and have a look around.
- Run `gradle tasks` to see the built-in tasks.
- Apply a plugin and run `gradle tasks` and `gradle properties` to see what it did.
- Run one of the tasks.
- Define a new task to extend whatever the plugin does.

**Comment by lacasseio** [comment]
Issue moved to [gradle/guides #252](https://github.com/gradle/guides/issues/252) via [**ZenHub**](https://www.zenhub.com/)
