### ISSUE TITLE
Build for this guide should absolutely not accept the build scan terms and conditions on behalf of the user

### ISSUE THREAD

**Issue by adammurdoch** [gradle-guides/creating-new-gradle-builds#24]
This is really bad form for an open source project: https://github.com/gradle-guides/creating-new-gradle-builds/blob/master/build.gradle.kts#L14

**Comment by lacasseio** [comment]
Issue moved to [gradle/guides #253](https://github.com/gradle/guides/issues/253) via [**ZenHub**](https://www.zenhub.com/)
