### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by deveras** [gradle-guides/creating-new-gradle-builds#26]
Hi guys,

Spotted something in the docs. Tried to add:
description = "A trivial Gradle build"
version = "1.0"

to the top of my build.gradle, but when i executed ./gradlew properties i get:
FAILURE: Build failed with an exception.

I then moved the lines to the end of the file and the command executed. Perhaps this will be a bit better:

You can change many of the properties. For example, you might try adding the following lines to **the end of** your build script file, and re-execute gradle properties.

**Comment by lacasseio** [comment]
Issue moved to [gradle/guides #241](https://github.com/gradle/guides/issues/241) via [**ZenHub**](https://www.zenhub.com/)
