### ISSUE TITLE
Example build fails

### ISSUE THREAD

**Issue by NorthPoleLars** [gradle-guides/creating-new-gradle-builds#29]
Just installed Gradle 5.0 and following instructions on https://guides.gradle.org/creating-new-gradle-builds/.

It doesn't work as expected:

mbp-09:gradle-demo {{username}}$ ./gradlew copy
Downloading https://services.gradle.org/distributions/gradle-5.0-bin.zip  <-- what caused this?
[version.txt](https://github.com/gradle-guides/creating-new-gradle-builds/files/2707643/version.txt)

............................................^Cmbp-09:gradle-demo larry.wilson$ ls
build.gradle.kts	gradlew			settings.gradle.kts
gradle			gradlew.bat		src
mbp-09:gradle-demo {{username}}$ nano build.gradle.kts 
mbp-09:gradle-demo {{username}}$ ./gradlew copy
Downloading https://services.gradle.org/distributions/gradle-5.0-bin.zip
.................................................................................

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'gradle-demo'.
> Could not open cache directory 4qulew5h20dqkqz3cd88iw7f2 (/Users/{{username}}/.gradle/caches/5.0/gradle-kotlin-dsl/4qulew5h20dqkqz3cd88iw7f2).
   > /Users/{{username}}/idea-projects/gradle-demo/build.gradle.kts:13:1: Unexpected `plugins` block found. Only one `plugins` block is allowed per script.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 33s
mbp-09:gradle-demo {{username}}$ 

[gradle-demo.zip](https://github.com/gradle-guides/creating-new-gradle-builds/files/2707640/gradle-demo.zip)

[version.txt](https://github.com/gradle-guides/creating-new-gradle-builds/files/2707644/version.txt)

**Comment by lacasseio** [comment]
Issue moved to [gradle/guides #264](https://github.com/gradle/guides/issues/264) via [**ZenHub**](https://www.zenhub.com/)
