### ISSUE TITLE
Describe build scans setup early on

### ISSUE THREAD

**Issue by etiennestuder** [gradle-guides/creating-new-gradle-builds#3]
‘Creating new Gradle builds’ should already describe enabling the build scan plugin. It’s an essential tool from day 1, also for people new to Gradle.

I've also created an issue to add a section to all guides on how to enable build scans. I'm opening this separate issue here because we should resolve this one in any case.

**Comment by etiennestuder** [comment]
@pioterj @ysb33r Here's my feedback, as you had requested.

**Comment by pioterj** [comment]
@ysb33r @kousen Please consider this for the launch.

**Comment by eriwen** [comment]
I hope this is properly addressed by my PR #13. I'd love your review of this.

**Comment by pioterj** [comment]
I'd lost track of this one. Very good improvements in the PR!

**Comment by lacasseio** [comment]
This seems to be addressed in PR https://github.com/gradle-guides/creating-new-gradle-builds/pull/13. Closing now, if it's not, please open a new issue with the next step.
