### ISSUE TITLE
basic example improvements and questions

### ISSUE THREAD

**Issue by InannaInai** [gradle-guides/creating-new-gradle-builds#39]
Dear authors,

I've tried to recreate the examples of: https://guides.gradle.org/creating-new-gradle-builds/

I'd like to add some improvements and questions to the code:

1) ./gradlew copy
As I'm using Windows it should be .\gradlew copy

2) Proxy
the 1) did not work for me as the command was not correct for windows AND I had not specified the proxys. Took me quite some time to find the solution
add gradle.propperties and in there add:
systemProp.https.proxyHost=HOSTNAME
systemProp.https.proxyPort=ProxyPort (8080 or so)
And add the same to gradle/wrapper/gradle-wrapper.properties

3) gradle --scan
I got this error:
**Publishing build scan failed due to network error 'java.net.SocketTimeoutException: connect timed out'**
I assume its an other proxy error
But I did not finde the solution yet

**Comment by lacasseio** [comment]
Issue moved to [gradle/guides #301](https://github.com/gradle/guides/issues/301) via [**ZenHub**](https://www.zenhub.com/)
