### ISSUE TITLE
Create android app from comand line

### ISSUE THREAD

**Issue by frog-o** [gradle-guides/creating-new-gradle-builds#40]
I was seaching everywhere to try to figure out how to create a new android app  **with out android studios** useing gradle (I dont like there ide).
 
I read on you site if you think something is missing from the gradles doc make an issue so I am here.  

I think it is a little off topic, but still  important 

 https://developer.okta.com/blog/2018/08/10/basic-android-without-an-ide

I think something like this with the explaintion of gradle wrapper and local.propertes are of greate importance for anyone that want to build android from the command line.

Why would you document android studios and not the command line wich gradle is ment to run on?

I would greatly appreciate it, If you do.
 
Could you, If  you don't mind  putting a link to this or create a more detail version? I still don't know why there no assembleDebug target maybe editing the local.properties  with the sdk path will help this. 

I wasted all yesterday going thou  your docs and internet seaching for this.

**Comment by lacasseio** [comment]
Issue moved to [gradle/guides #302](https://github.com/gradle/guides/issues/302) via [**ZenHub**](https://www.zenhub.com/)
